version: '3.5'

networks:
  php-node-sqlsrv-nginx:

services:
  nginx:
    image: nginx
    container_name: nginx_app
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - php-node-sqlsrv-nginx
    working_dir: /var/www
  php:
      image: php-node-sqlsrv
      container_name: php_app
      volumes:
        - ./:/var/www
      working_dir: /var/www
      ports:
        - '9092:9000'
      environment:
        PHP_MEMORY_LIMIT: 1G
        APP_ENV: dev
        APP_SECRET: 7d41a4acde33432b1d51eae15a301550
      networks:
            - php-node-sqlsrv-nginx